Additional Sbtc clarity mini tests
stacks-network/sbtc pull request #148
Opened 2023-09-18 14:20 UTC by setzeus

# sBTC Clarity-Bitcoin-Mini Tests
## Summary of Changes

This PR is meant to add a handful of Clarity unit tests for the clarity-bitcoin-mini.clar file found in romeo/asset-contract. 

## Testing

### Risks

Please list, loosely, the risks that are associated with this PR. This can be very short. Even a documentation update would have the risk that the added information misleads a user to do or think XYZ.

### How were these changes tested?

Please describe the following:
1. What tests you ran to verify your changes
2. How to replicate these tests
3. Any relevant details for your test configuration

### What future testing should occur?

Please list known edge cases or tests that need further testing that don't make sense to add in this PR (integration tests and the like). **Once this PR is approved create an issue for each item and update the following section in the PR description so each bullet has an associated ticket next to it.**

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-09-18 14:46 UTC, AshtonStephens commented
I think this is the first use of the testing standards doc template and this is a perfect example of how to use it! 10/10 this PR is awesome.

2023-09-18 17:13 UTC, jo-tm approved these changes
LGTM

2023-09-18 17:35 UTC, friedger requested changes
While the test passes, I have some nit.

Also I think it might be good to have the proofs in a list, so that it is very easy to add more. Or to replace an existing one with one that I would like to test from my development environment.

For the failed verification, it would be good to be more explicit why they fail.

2023-09-18 17:35 UTC, friedger commented on romeo/asset-contract/tests/clarity-bitcoin-mini_test.clar
> +        ;; prepare
why is this `prepare`?

2023-09-18 17:35 UTC, friedger commented on romeo/asset-contract/tests/clarity-bitcoin-mini_test.clar
> +        (ok (is-err (contract-call? .clarity-bitcoin-mini verify-merkle-proof
Which error do we expect?

2023-09-18 17:35 UTC, friedger commented on romeo/asset-contract/tests/clarity-bitcoin-mini_test.clar
> +            (ok (contract-call? .clarity-bitcoin-mini verify-merkle-proof
Do we expect `(ok (ok true))` here?

2023-09-18 17:35 UTC, friedger commented on romeo/asset-contract/tests/clarity-bitcoin-mini_test.clar
> +        (ok (is-err (contract-call? .clarity-bitcoin-mini verify-merkle-proof
Do we have a test for proof too short?

2023-09-18 17:35 UTC, friedger commented on romeo/asset-contract/tests/clarity-bitcoin-mini_test.clar
> +(define-constant zero-address 'SP000000000000000000002Q6VF78)
Why do we need this constant?

2023-09-18 17:35 UTC, friedger commented on romeo/asset-contract/tests/clarity-bitcoin-mini_test.clar
> +            (ok (contract-call? .clarity-bitcoin-mini verify-merkle-proof
Is the result always `true`?

2023-09-22 06:15 UTC, friedger commented
@MarvinJanssen mentioned some helper functions for asserts. I didn't find them in https://github.com/search?q=repo%3ATrust-Machines%2Fstacks-sbtc+asserts&type=code

2023-09-22 10:39 UTC, setzeus commented
@friedger think he meant like the (assert-eq ...) & (assert-all-eq ...) found here: https://github.com/Trust-Machines/stacks-sbtc/blob/main/sbtc-mini/tests/sbtc-registry_test.clar

2023-09-22 12:23 UTC, friedger approved these changes
Looks good

2023-09-22 20:19 UTC, friedger commented
@setzeus It would be nice to use these asserts-eq functions

2023-09-25 17:49 UTC, jo-tm approved these changes
LGTM

2023-09-25 18:05 UTC, merged