Add check for contract versions via clarinet-sdk
stacks-network/sbtc pull request #173
Opened 2023-09-27 06:41 UTC by friedger

## Description
This PR 
* adds a unit test to check that the contract versions of `clarity-bitcoin-mini` differ only in DEBUG flag
* introduces clarinet-sdk to this repo
* fixes #172

2023-09-27 09:59 UTC, stjepangolemac commented
What does this concretely mean for Romeo? Does it change how we deploy or test contracts? Is it related to interpolating env vars into contracts that we mentioned the other day?

2023-09-27 12:04 UTC, friedger commented
If adopted, Clarinet-sdk changes the way we test contracts. 

Clarinet-sdk can create new contracts based on env vars.

For deployments, I am not sure whether the SDK supports that or we continue with the current solution. Maybe @hugocaillard can comment.

2023-09-27 13:22 UTC, hugocaillard commented
The clarinet-sdk only replaces the `clarinet test` and `clarinet run` features. It has no impact on deployment.

This PR looks good to me 👌 

You may have one issue **while moving from `clarinet test` to the SDK** for testing, regarding the test file notation with `.test.ts` or `_test.ts`:

- `npm test` (with vitest) won't try to run the `tests/*_test.ts` files (by default, vitest checks `*.test.ts`)
- **but** i think that `clarinet test` might try to execute both `*_test.ts` and `*.test.ts`


I think you'll need to run `clarinet test tests/*_test.ts` instead of just `clarinet test`. And again, this is just until all tests are migrated to Node.js

2023-09-28 17:19 UTC, lgalabru commented
I think `clarinet-sdk` would simplify a lot of things in this repo, for instance, the whole layer generating tests [here](https://github.com/stacks-network/sbtc/blob/main/romeo/asset-contract/ext/generate-tests.ts) could be dropped.
This new sdk was designed to:
- help developers test their smart contracts (so similar to `clarinet test`)
- help developers design their own test harnessing framework, by exposing all the functions for building on top Clarity VMs at a low level, which is new. 
With this new design, creating a npm library that would help developers writing clarity for testing clarity, or a lib for fuzz testing clarity code should be relatively straightforward and more robust.
Feel free to ping us if you think that a meeting / crash course could help and accelerate this transition.

2023-10-02 18:51 UTC, setzeus commented on romeo/asset-contract/tests/clarity-bitcoin-mini-deploy.test.ts
> +  it("ensures the versions differ only in DEBUG flag", () => {
Appreciate the comment here - answers my question on what's the difference b/w both contract.

2023-10-02 18:52 UTC, setzeus approved these changes
Changes LGTM but can you point me to more context / docs on Clarinet-SDK?

2023-10-02 21:23 UTC, hugocaillard commented
@setzeus There's some context on [discord](https://discord.com/channels/621759717756370964/839633619261456444/1154096301986811975). But the official docs and a blog post will be available this week, along with the v1.0

2023-10-03 14:20 UTC, hugocaillard commented on romeo/asset-contract/tests/clarity-bitcoin-mini-deploy.test.ts
> +});
```suggestion
```

This is now the default behavior of the test framework, so it's not needed anymore.

And this it what appears to make the test fail right now.

cc @friedger

2023-10-04 17:29 UTC, hugocaillard requested changes
@friedger 

We wanted to make a pretty important breaking change before the release of v1.
The name `vm` (`ClarityVM` and `initVM`) didn't make sense as it kind of refers to the Clarity VM, but what we are really interacting with in the SDK is the `simnet`.

So we reworded that. PR [here](https://github.com/hirosystems/clarinet/pull/1181) for full context.

Thanks for bearing with us in these early stage version of the SDK. 

This v0.9 is very likely to be promoted to v1 🙌 

PS: ofc feel free to commit my suggestion or make your own commit with everything in it

2023-10-04 17:29 UTC, hugocaillard commented on romeo/asset-contract/package.json
> +    "@hirosystems/clarinet-sdk": "^0.6.4",
```suggestion
    "@hirosystems/clarinet-sdk": "^0.9.0",
```

(will require to re-run `npm install` to apply changes in the package-lock.json)

2023-10-04 17:29 UTC, hugocaillard commented on romeo/asset-contract/package.json
> +    "vitest-environment-clarinet": "^0.1.1"
```suggestion
    "vitest-environment-clarinet": "^0.2.0"
```

(will require to re-run `npm install` to apply changes in the package-lock.json)

2023-10-04 17:29 UTC, hugocaillard commented on romeo/asset-contract/scripts/generate-docs.ts
> +  initVM,
```suggestion
  initSimnet,
```

2023-10-04 17:29 UTC, hugocaillard commented on romeo/asset-contract/tests/clarity-bitcoin-mini-deploy.test.ts
> +    const sourceForDeploy = vm.getContractSource(
```suggestion
    const sourceForUnitTests = simnet.getContractSource("clarity-bitcoin-mini")!;
    const sourceForDeploy = simnet.getContractSource(
```

2023-10-04 17:29 UTC, hugocaillard commented on romeo/asset-contract/scripts/generate-docs.ts
> +    const source = vm.getContractSource(contractId);
```suggestion
  const simnet = await initVM();
  for (let [contractId, abi] of simnet.getContractsInterfaces()) {
    const ast = simnet.getContractAST(contractId);
    const source = simnet.getContractSource(contractId);
```

2023-10-05 10:48 UTC, setzeus approved these changes

2023-10-05 12:08 UTC, MarvinJanssen approved these changes

2023-10-05 12:08 UTC, MarvinJanssen commented on romeo/asset-contract/tests/clarity-bitcoin-mini-deploy.test.ts
> +        "(define-constant DEBUG-MODE false)"
Some extra white space can kill this test. For now it is OK, perhaps in the future we can compare AST.

2023-10-05 12:08 UTC, merged