feat: lock sBTC when initializing withdrawal
stacks-network/sbtc pull request #200
Opened 2024-05-28 19:38 UTC by hstove

This uses the new sBTC token contract to properly lock the user's sBTC when they initialize a withdrawal request.

2024-05-29 14:27 UTC, setzeus requested changes
Overall looks great, maybe just add a test to cover withdrawing less than the dust amount? Once that's included will be good to merge.

2024-05-29 16:44 UTC, hstove commented
Good call @setzeus , ready for re-review!

2024-05-30 12:53 UTC, setzeus approved these changes

2024-05-30 19:01 UTC, friedger commented on contracts/tests/sbtc-withdrawal.test.ts
> +  test("Cannot try and withdrawal less than or equal to the dust limit", () => {
nit: To match the pattern above "test withdrawal amount of less than or equal to the dust limit is rejected"

2024-06-05 01:11 UTC, hstove commented on contracts/contracts/sbtc-withdrawal.clar
> +(define-constant dust-limit u546)
Yeah, the dust limit is a constant (it matches the BTC dust limit). In this case, it's the minimum amount you can withdrawal. Fees are dynamic, but they're on top of your "withdrawal amount", so this dust limit is still applicable

2024-06-12 19:51 UTC, setzeus commented
@friedger I fixed the broken test, can you re-review when you have a few mins here? Hank is OOO for the next few weeks & I'd like to get this merged in asap.

2024-06-14 13:59 UTC, friedger commented on contracts/contracts/sbtc-withdrawal.clar
> +(define-constant dust-limit u546)
Who pays for the fees of withdrawal?
What happens when I want to withdraw dust + 1 sat?

2024-06-18 15:36 UTC, radicleart commented
Any links to the design docs to get a feel for the overall flow ?

2024-06-18 15:48 UTC, radicleart commented
The token contract could explicitly declare impl-trait for sip 10 ? What are the guidelines on this? 

Also the token name is "sBTC Mini" is this right ?

2024-06-18 16:04 UTC, radicleart reviewed
Looks good !

2024-06-19 01:09 UTC, setzeus commented
> Any links to the design docs to get a feel for the overall flow ?

Yeap! https://docs.google.com/document/d/1Bwi1jM_7p9OqNGT41eWCuoKnfoOrNHycqxby3XSonCA/edit?usp=sharing

2024-06-19 01:17 UTC, setzeus commented
> The token contract could explicitly declare impl-trait for sip 10 ? What are the guidelines on this?
> 
> Also the token name is "sBTC Mini" is this right ?

Ah, thank you, caught & updated.

2024-06-19 13:10 UTC, radicleart approved these changes
Looks good .

2024-06-19 13:22 UTC, merged